# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 01901e83aeb9c1f95bd79e2a2d1c612068f5013fe6b71e8ede864b5e54410e6e5c492368a66699841be82cbc292d7b9e2dfb1974b76f209a8eb0d17180fafaf4

test:
  secret_key_base: e837d0464799573ee8d22c27661e4f86fc169074b99e4cde2582f20daef255d8a2c92e44847c5c1d61af15e0654a112b221b7329822fbea9a90bd5bc62500aab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
